version: "3"
services:
  localstack:
    container_name: court-case-localstack
    image: localstack/localstack
    networks:
      - hmpps
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=sqs,sns
      - PORT_WEB_UI=9080
      - DEBUG=${DEBUG:-0}
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  hmpps:
