apiVersion: v1
kind: Pod
metadata:
  name: pg-dump-pod
spec:
  containers:
    - image: bitnami/postgresql
      name: pg-dump-pod
      volumeMounts:
        - mountPath: /data
          name: data-volume

      env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
  volumes:
    - name: data-volume
      emptyDir: {}
